#高可用eureka集群
server:
  port: 8762
eureka:
  instance:
    hostname: eureka8762
    # 服务续约（心跳）频率，单位：秒，缺省30
#    lease-renewal-interval-in-seconds: 1
    # 服务失效时间，失效的服务将被剔除。单位：秒，默认：90
#    lease-expiration-duration-in-seconds: 1

  server:
  # 是否允许开启自我保护模式，缺省：true 当Eureka服务器在短时间内丢失过多客户端时，自我保护模式可使服务端不再删除失去连接的客户端
    enable-self-preservation: false
  # 每间隔 2s，向服务端发送一次心跳，证明自己依然"存活"
    lease-renewal-interval-in-seconds: 2
  # 告诉服务端，如果我 10s 之内没有给你发心跳，就代表我故障了，将我踢出掉
    lease-expiration-duration-in-seconds: 10
  # Peer节点更新间隔，单位：毫秒
#    peer-eureka-nodes-update-interval-ms: 60000
  # Eureka服务器清理无效节点的时间间隔，单位：毫秒，缺省：60000，即60秒
#    eviction-interval-timer-in-ms: 60000

  client:
  # 是否向注册中心注册自己，缺省：true 一般情况下，Eureka服务端是不需要再注册自己的service
    register-with-eureka: false
  # 是否从Eureka获取注册信息，缺省：true 一般情况下，Eureka服务端是不需要检索其它服务
    fetch-registry: false
#    eureka.client.register-with-eureka：false与fetch-registry：false  表明当前服务是一个eureka server.
    serviceUrl:
      defaultZone: http://eureka8761:8761/eureka/