eureka:
  client:
    serviceUrl:
#      defaultZone: http://192.168.29.136:9091/eureka/
#      defaultZone: http://eureka-k8s-service:9091/eureka/
      defaultZone: http://localhost:9091/eureka/
server:
  port: 11101
spring:
  application:
    name: flight-service
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
# sh startup.sh -m standalone
#  zipkin:
#    base-url: http://localhost:9411
#    sender:
#      type: web
#  sleuth:
#    sampler:
#      percentage: 1.0
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic